// Accurately sourced Islamic quotations for the daily reminder.
// Every entry includes its source/reference. Never fabricate.

export const QUOTES = [
  { text: "Indeed, in the remembrance of Allah do hearts find rest.", source: "Quran 13:28", category: "Remembrance" },
  { text: "So remember Me; I will remember you. And be grateful to Me and do not deny Me.", source: "Quran 2:152", category: "Gratitude" },
  { text: "And seek help through patience and prayer. Indeed, it is burdensome except for the humble.", source: "Quran 2:45", category: "Prayer" },
  { text: "Indeed, with hardship comes ease.", source: "Quran 94:6", category: "Patience" },
  { text: "And establish prayer for My remembrance.", source: "Quran 20:14", category: "Prayer" },
  { text: "Indeed, Allah is with those who are patient.", source: "Quran 2:153", category: "Patience" },
  { text: "When My servants ask you concerning Me, indeed I am near. I respond to the call of the caller when he calls upon Me.", source: "Quran 2:186", category: "Hope" },
  { text: "And do not lose hope in the mercy of Allah. Indeed, Allah forgives all sins.", source: "Quran 39:53", category: "Mercy" },
  { text: "Indeed, Allah does not burden a soul beyond that it can bear.", source: "Quran 2:286", category: "Perseverance" },
  { text: "Call upon Me; I will respond to you.", source: "Quran 40:60", category: "Tawakkul" },
  { text: "And whoever relies upon Allah, He will be sufficient for him.", source: "Quran 65:3", category: "Tawakkul" },
  { text: "The most beloved of deeds to Allah are those done consistently, even if they are few.", source: "Sahih al-Bukhari 6464, Sahih Muslim 783", category: "Perseverance" },
  { text: "Take on only as much as you can do of good deeds, for the best of deeds are those done consistently.", source: "Sahih al-Bukhari 43, Sahih Muslim 783", category: "Perseverance" },
  { text: "The strong believer is better and more beloved to Allah than the weak believer, though in both there is good.", source: "Sahih Muslim 2664", category: "Perseverance" },
  { text: "Whoever persists in seeking forgiveness, Allah will appoint for him a way out of every distress and a relief from every worry.", source: "Sunan Abi Dawud 1518", category: "Mercy" },
  { text: "The one who recites the Quran and is skilled in it is with the noble, righteous scribes.", source: "Sahih al-Bukhari 4937, Sahih Muslim 798", category: "Quran" },
  { text: "Whoever reads a letter from the Book of Allah earns a good deed, and each good deed is multiplied tenfold.", source: "Jami at-Tirmidhi 2910", category: "Quran" },
  { text: "There is a piece of flesh in the body: if it is sound, the whole body is sound; if it is corrupt, the whole body is corrupt — and that is the heart.", source: "Sahih al-Bukhari 52, Sahih Muslim 1599", category: "Remembrance" },
  { text: "Smiling in the face of your brother is charity.", source: "Jami at-Tirmidhi 1956", category: "Mercy" },
  { text: "The most beloved of places to Allah are the masjids.", source: "Sahih Muslim 668", category: "Prayer" },
  { text: "Allah is beautiful and loves beauty.", source: "Sahih Muslim 91", category: "Gratitude" },
  { text: "Whoever Allah intends good for, He gives him understanding of the religion.", source: "Sahih al-Bukhari 71, Sahih Muslim 1037", category: "Quran" },
  { text: "Indeed, good deeds wipe away bad deeds. That is a reminder for those who remember.", source: "Quran 11:114", category: "New beginnings" },
  { text: "Say: My Lord has guided me to a straight path, a right religion, the way of Abraham, inclining toward truth.", source: "Quran 6:161", category: "Prayer" },
  { text: "And He found you lost and guided you.", source: "Quran 93:7", category: "New beginnings" },
  { text: "Indeed, your Lord is vast in forgiveness.", source: "Quran 53:32", category: "Mercy" },
  { text: "And that it is My remembrance of which you are not heedless.", source: "Quran 87:9", category: "Remembrance" },
  { text: "So be patient with what your Lord has decreed.", source: "Quran 52:48", category: "Patience" },
  { text: "And We have certainly made the Quran easy for remembrance, so is there any who will remember?", source: "Quran 54:17", category: "Quran" },
  { text: "Glorify the praises of your Lord before the rising of the sun and before its setting.", source: "Quran 50:39", category: "Dhikr" },
];